language: python
before_install:
- sudo add-apt-repository --yes ppa:fontforge/fontforge
- sudo apt-get update -qq
- sudo apt-get install python-fontforge
- cp /usr/lib/python2.7/dist-packages/fontforge.* "$HOME/virtualenv/python2.7.8/lib/python2.7/site-packages"
install:
- pip install git+https://github.com/behdad/fontTools.git
- pip install git+https://github.com/googlefonts/fontbakery-cli.git
- pip install jinja2
script: PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH fontbakery.py .
branches:
  only:
  - master
after_success:
- rm -rf builds/build/sources builds/build/build.state.yaml
- PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH bakery-report.py builds/build
- PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH travis-deploy.py
env:
  global:
    secure: RTVieEbpWQ4T/A2wAQWkepogUQqvOabrAI8RF5Kzvso3IaRWFm9TjGY9z9RgcYwzSH0YN05fMW8XTN1/WnFGRKwwvSKhFHXy2gSnbWxDHgddgByA2TNN9lwgTW5sQTyzF4KquiRczmSyqEGXpxSgV142dTfkgheW1ZgrFBhMnLE=
