language: python
before_install:
- sudo add-apt-repository --yes ppa:fontforge/fontforge
- sudo apt-get update -qq
- sudo apt-get install python-fontforge
- cp /usr/lib/python2.7/dist-packages/fontforge.* "$HOME/virtualenv/python2.7.8/lib/python2.7/site-packages"
install:
- pip install git+https://github.com/behdad/fontTools.git
- pip install git+https://github.com/googlefonts/fontbakery-cli.git
- pip install jinja2
script: PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH fontbakery.py . | tee builds/build/build.log
branches:
  only:
  - master
after_script:
- rm -rf builds/build/sources
- PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH bakery-report.py --with-upstream-tests=.upstream.yaml builds/build
- PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH travis-deploy.py
- rm -rf builds/build/build.state.yaml
env:
  global:
    secure: nexLlj3kidO2xEqk9wuIypEbzQ4mOV44pvrFT7UJVcJDeOe/hugLvGkJU0v/kr8pw7Cc7hLWH5gyu+T4aNf+26GCawDw+LVGN3WUodRRoaIdLebSAvvk+6AM3F2WncgthGMFMWpdw5qQJuh5FK+3bCnvv55ECYOZ5RbNSsfeXlw=
